# Generated by Django 5.0 on 2024-01-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star5', models.IntegerField(default=0)),
                ('star4', models.IntegerField(default=0)),
                ('star3', models.IntegerField(default=0)),
                ('star2', models.IntegerField(default=0)),
                ('star1', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rating_table',
            },
        ),
    ]
