# Generated by Django 5.0 on 2024-02-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
