# Generated by Django 5.0 on 2024-02-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_favobject_delete_achievement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favobject',
            old_name='vuz',
            new_name='vuz_or_razdel',
        ),
    ]
