# Generated by Django 5.0 on 2024-02-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_favobject_delete_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favobject',
            name='vuz',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
