# Generated by Django 5.0 on 2023-12-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_testing', '0002_test_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='correct_answer',
            field=models.CharField(),
        ),
    ]
