# Generated by Django 5.0 on 2024-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllIndividualAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name_event', models.TextField()),
            ],
            options={
                'db_table': 'all_ind_achives',
            },
        ),
    ]
